### ISSUE TITLE
Add twitter bootstrap to front

### ISSUE THREAD

**Issue by electblake** [buttercoin/buttercoin#10]
I understand that there are bigger fish to fry, but I like having pretty/extensible UIs to work with. I've already converted index.html & /public to twitter bootstrap + handlebars. If issue gets comment(s)/approved I'll send merge req.

**Comment by JulianNorton** [comment]
this! I can finally help out as I'm a designer, not a programmer.

**Comment by electblake** [comment]
lol, well - hacking around and I think that #2 might need to be addressed (at least for front) don't want to complicate the core goal(s) (the engine/api)

But, checkout my fork for the starts, I might try to isolate front a bit (or rip it out into a new project relying on api's solely)

@JulianNorton should make some logo options for community review heh. Who doesn't like a slick logo ;)

**Comment by Marak** [comment]
- 1 for improving the content of the `/public/` folder!

**Comment by electblake** [comment]
@JulianNorton & trolls, closing in favour of more atomic issues regarding further development re:front
