### ISSUE TITLE
Please consider making it public domain software

### ISSUE THREAD

**Issue by artob** [buttercoin/buttercoin#13]
If you're [liberty-minded](http://mises.org/daily/4601), you may wish to have a look at http://unlicense.org/ for instructions on how to put the software into the [public domain](http://stpeter.im/writings/essays/publicdomain.html), which would make this project all the more interesting for everybody similarly inclined who might wish to contribute.

**Comment by leashless** [comment]
It has certainly worked very well for my open hardware project (http://hexayurt.com) which has been public domain from the beginning - to avoid patent license hell, among other reasons. There are few cases where, if the idea is a good one and derivative works are also socially useful, where there's any need for a more restrictive license.

**Comment by avwhite** [comment]
My understanding is that public domain is somewhat wired and ambiguous to work with. Some countries (e.g. Germany) don't even acknowledge the concept. From what I have heard just using a really permissive license like MIT is easier.

I don't have any personal experience with it though.

**Comment by artob** [comment]
@ismettern, that's why explicit, formalized public-domain dedications such as [Creative Commons Zero](http://creativecommons.org/publicdomain/zero/1.0/) or the [Unlicense](http://unlicense.org) are designed to be crystal clear about the author's intent so that if need be they can be interpreted as maximally-permissive licenses as a fallback strategy. See [Dissecting the Unlicense: Software Freedom in Four Clauses and a Link](http://ar.to/2010/01/dissecting-the-unlicense) for some particulars.

The Unlicense was inspired by the hugely-successful [SQLite](http://sqlite.org) project, which has certainly not been impeded by being in the public domain; [quite the contrary](http://sqlite.org/mostdeployed.html), it is installed on virtually every desktop or laptop computer plus every iPhone or Android smartphone today.

**Comment by enki** [comment]
it already is MIT - what's your problem with that?

**Comment by mikegogulski** [comment]
+1. Even the MIt license, lovely though it is, pretends justice in attaching duties to others.

**Comment by enki** [comment]
ok, but that's legalese that protects us. sorry, MIT is as free as you get in a system with lawyers.

**Comment by mikegogulski** [comment]
Unproven statement, and one I believe to be untrue, but no ill feelings. Glad to see someone's going full tilt at a big challenge in the Bitcoin sphere.

**Comment by PartTimeLegend** [comment]
NACK
