### ISSUE TITLE
Travis Hooks

### ISSUE THREAD

**Issue by PartTimeLegend** [buttercoin/buttercoin#25]
I tried to get this raised on IRC, but was met with some hostility.

We have a series of unit tests in `tests` with a shell script `test.sh` to execute these.

There is a YAML file called `.travis.yml` which will tell [Travis CI](https://travis-ci.org) how to execute these tests.

Git repo admin needs to login to Travis and enable the testing for this repo.

This will run all the tests again any commits, pulls, branches, etc.

If this could get actioned, it would be appreciated.

**Comment by enki** [comment]
hostility? why? i'll look into adding it - need to rush off to a meeting tho

talk later

**Comment by enki** [comment]
ok integrated
