### ISSUE TITLE
Unit Tests Fail After Pull Merged

### ISSUE THREAD

**Issue by PartTimeLegend** [buttercoin/buttercoin#27]
[This pull](https://github.com/buttercoin/buttercoin/pull/26) was merged whilst I was checking the test changes. The tests however fail, and this was committed to `master`. It either needs to be rolled back or amended to fix.

>  Api
>     ◦ should initialize:   ✓ should initialize 
>     ◦ should start and provide a WS server: info: Buttercoin api server started on ws://0.0.0.0:3022
> called api callback
>   ✓ should start and provide a WS server 
>   Market
>     ◦ should initialize with a buy book and a sell book:   ✓ should initialize with a buy book and a sell book 
> info: api server receiving incoming wss connection from localhost:3022
>   Currency
>     ◦ should initialize with an empty balance:   ✓ should initialize with an empty balance 
>     ◦ should be possible to cumulatively add to the balance:   ✓ should be possible to cumulatively add to the balance 
>   DataStore
>     ◦ should initialize with a balance sheet and supermarket:   ✓ should initialize with a balance sheet and supermarket 
>     #add_order
>       ◦ should ?:   ✓ should ? 
>     #add_deposit
>       ◦ should create accounts as needed, apply deposit and return the new balance of the account:   ✓ should create accounts as needed, apply deposit and return the new balance of the account 
>   BalanceSheet
>     ◦ should initialize with no accounts:   ✓ should initialize with no accounts 
>     ◦ should add new account instances as they are requested if and only if they dont already exist:   ✓ should add new account instances as they are requested if and only if they dont already exist 
>   Account
>     ◦ should initialize with no currencies:   ✓ should initialize with no currencies 
>     ◦ should add new currency instances as they are requested if and only if they dont already exist:   ✓ should add new currency instances as they are requested if and only if they dont already exist 
>   SuperMarket
>     ◦ should initialize with no markets:   ✓ should initialize with no markets 
>     ◦ should add new market instances as they are requested if and only if they dont already exist:   ✓ should add new market instances as they are requested if and only if they dont already exist 
>   Front
>     ◦ should initialize:   ✓ should initialize 
>     ◦ should start a WSS:   ✓ should start a WSS (197ms)
> info: Buttercoin front-end server started on http://0.0.0.0:3020
> warn: front attempting to log in to ws://localhost:3021
>     ◦ should connect to the API:   ✓ should connect to the API 
>   TradeEngine
>     ◦ can initialize: Stub got a connection
> info: front connected to ws://localhost:3021
> LOG DOES NOT EXIST
>   1) can initialize
> INITIALIZING LOG
>   ✖ 1 of 18 tests failed:
>   1) TradeEngine can initialize:
>      Error: socket hang up
>       at createHangUpError (http.js:1373:15)
>       at Socket.socketOnEnd [as onend](http.js:1470:23)
>       at TCP.onread (net.js:419:26)
> npm ERR! Test failed.  See above for more details.
> npm ERR! not ok code 0
> The command "npm test" exited with 1.
> Done. Your build exited with 1.

**Comment by Marak** [comment]
We are actively working on this code path in the IRC room. Please feel free to join us.
