### ISSUE TITLE
Use of objects as hashmaps without hasOwnProperty guard

### ISSUE THREAD

**Issue by pyalot** [buttercoin/buttercoin#3]
Datastore uses objects as hashmaps:
- https://github.com/buttercoin/buttercoin/blob/master/lib/datastore.coffee#L14
- https://github.com/buttercoin/buttercoin/blob/master/lib/datastore.coffee#L24

Use of these then happens by accessing the hashmap to store or retrieve a value by key:
- https://github.com/buttercoin/buttercoin/blob/master/lib/datastore.coffee#L19
- https://github.com/buttercoin/buttercoin/blob/master/lib/datastore.coffee#L29

Some of the keys might be user supplied, and can be things such as "Joe", "1234" or "toString", "constructor" etc.

So before setting a property on an object from user supplied values, you will have to check with hasOwnProperty if that property is available. However this presents a problem, since the key could also be "hasOwnProperty"

``` javascript
>>> a = {}
Object {}
>>> a.hasOwnProperty('hasOwnProperty')
false
>>> a['hasOwnProperty'] = 'asdf'
"asdf"
>>> a.hasOwnProperty('hasOwnProperty')
TypeError: Property 'hasOwnProperty' of object #<Object> is not a function
```

Read more about this issue there: http://www.devthought.com/2012/01/18/an-object-is-not-a-hash/

**Comment by shesek** [comment]
- You can use `Object::hasOwnProperty.call obj, 'hasOwnProperty'`
- Using `obj = Object.create null` can be used to create an object that doesn't inherit any of the built-in methods, which is safer to use as a dictionary
- You can also prefix the keys with some string to avoid collisions with built-in properties, i.e. `obj['$'+key]`
- I would personally not bother with all that except for when dealing with user-supplied values, or when the possible keys are known to be problematic (for example, with the currencies, there's probably no need to do any of that)

**Comment by pyalot** [comment]
@shesek It's used in this code also for user accounts.

**Comment by enki** [comment]
thanks! will take care of that.

**Comment by shesek** [comment]
@pyalot yeah, I saw that. I'm just saying that it shouldn't be done on every place that uses an object as a dictionary,  but only where its problematic, like the Account case you linked to.

Also, it should probably be mentioned that objects created with `Object.create null` aren't perfect as dictionaries because of `__proto__` which is still problematic. Also, `Object.create` was added at ES5, so it wouldn't work well client-side if its ever needed there.

I would go with prefixing the keys - it resolves the `__proto__` issue and works on all javascript environments. You can even wrap it with something like that to make it more convenient to use:

``` coffee
class Dict
  constructor: (@storage = {}) ->
  get: (key) -> @storage['$' + key]
  set: (key, value) -> @storage['$' + key] = value
  has: (key) -> '$' + key of @storage
  delete: (key) -> delete @storage['$' + key]
  del: @::delete # just an alias, because `delete` is reserved and only works
                 # when used as `dict['delete']` and not `dict.delete`
                 # (which CoffeeScript does automatically, but `del`
                 # is more convenient for JS code)
```

**Comment by enki** [comment]
changed and added to coding pitfalls document

**Comment by pyalot** [comment]
Note that the upcoming harmony ES6 specification is probably going to specify Map and Set types. Firefox does have experimental implementations of them:

https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Map
https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Set

So far these objects are shimable (no support for iteration and square brackets yet). I would suggest to use a facility mocking these objects as a shim if not present.
