### ISSUE TITLE
Host Project Pages in New, Seperate Repo

### ISSUE THREAD

**Issue by liamja** [buttercoin/buttercoin#39]
The `gh-pages` branch should be moved to a new repo called `buttercoin.github.io`

This is advantageous as it will keep the main repo clean, commit logs clean, and will give us a cleaner URL to send people to.

**Comment by PartTimeLegend** [comment]
+1

**Comment by enki** [comment]
new repo created and access given - can you move it over?

**Comment by PartTimeLegend** [comment]
I've moved it. Please update DNS.

**Comment by enki** [comment]
dns is same as before

**Comment by PartTimeLegend** [comment]
Git history migrated and gh-pages branch removed from code repo.
