### ISSUE TITLE
Datastore uses boolean truthyness test on values retrieved from object

### ISSUE THREAD

**Issue by pyalot** [buttercoin/buttercoin#4]
The following places a value obtained from a data store object by user supplied key is subjected to a boolean truthyness test.
- https://github.com/buttercoin/buttercoin/blob/master/lib/datastore.coffee#L29
- https://github.com/buttercoin/buttercoin/blob/master/lib/datastore.coffee#L19

The key can be "Joe", "123", "MickeyMouseDollar" or "constructor", "hasOwnProperty" etc.

``` javascript
>>> a = {}
Object {}
>>> !a['Joe']
true
>>> !a['constructor']
false
>>> !a['hasOwnProperty']
false
```

The same result would ensue by comparisions against undefined, void 0, etc. I would suggest using instanceof.

``` javascript
>>> MyObj = function(){}
function (){}
>>> a['Joe'] instanceof MyObj
false
>>> a['constructor'] instanceof MyObj
false
>>> a['hasOwnProperty'] instanceof MyObj
false
>>> a['MickeyMouse'] = new MyObj()
MyObj {}
>>> a['MickeyMouse'] instanceof MyObj
true
```

**Comment by PartTimeLegend** [comment]
+1

**Comment by enki** [comment]
thanks! @pyalot do you want repo access?

**Comment by enki** [comment]
changed - probably need to add that to coding guidelines
