### ISSUE TITLE
bin/dev-standalone fails - Windows

### ISSUE THREAD

**Issue by ghost** [buttercoin/buttercoin#42]
The dev-standalone script runs the api before the engine is ready to accept connections.

If possible, wait for the engine to be ready. Otherwise, implement a hard timeout.

Seems like this is actually due to windows, which doesn't like to bind '0.0.0.0'

**Comment by PartTimeLegend** [comment]
Edited OP to reflect Windows issue.

I don't have a Windows machine ATM to test this on.

**Comment by Marak** [comment]
Should be fixed with https://github.com/buttercoin/buttercoin/commit/c69790c980513f963e940cb64e8cfb2d430aa632
