### ISSUE TITLE
authentication?

### ISSUE THREAD

**Issue by yubrew** [buttercoin/buttercoin#43]
We could start with existing, simple authentication for Node such as passport. If this is fine, then I can work on a pull with auth tests.

**Comment by PartTimeLegend** [comment]
Passport supports OAuth if memory serves. This means that a user can register with the site, login with google, login with twitter or facebook.

Is there an implementation of two factor authentication with passport?

**Comment by yubrew** [comment]
Correct, Passport has a ton of modules for different login methods. It doesn't appear to have a two-factor authentication module with passport.

However, there is a node implementation here with twilio that could work. Also, is two-factor auth inside / outside the scope of MVP?
http://www.twilio.com/blog/2012/04/two-factor-authentication-with-node-js-and-twilio.html

**Comment by Marak** [comment]
Passport might not be the best choice for authentication for an exchange. Providing the ability to login through other providers may not be safe or desired. 

Also, using a 3rd party module for auth could cause issues. Would not want to be in a situation where there could be upstream bugs or changes in our authentication code. It seems that it might be safer to have auth handled by a small module baked directly into the project.

@enki - Thoughts? If you think multiple login providers ( google / twitter / etc ) are desirable, we should probably use passport. If not, we should roll something small and custom.

**Comment by enki** [comment]
multiple login providers might be useful for various fraud prevention
strategies down the line - e.g. social network analysis - i'd make it
pluggable but we don't have to start with passport.

in general i think that large transfers will need secondary authentication
in any case.

passport seems simple enough - we could just start using it with only the
l/p code for now?
