### ISSUE TITLE
Not working on FreeBSD

### ISSUE THREAD

**Issue by ghost2501** [buttercoin/buttercoin#51]
Hi Guys,

I know it is a long shot but I have tried running Buttercoin on FreeBSD. If you expect that it should work can you please have a look at the logs below?

bsd# sh ./test.sh

  0 tests complete (4 ms)

done

bsd# npm start

> buttercoin@0.0.3 start /usr/home/ghostcorps/buttercoin-master
> bin/dev-standalone

Error: Cannot find module '../lib/buttercoin'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/home/ghostcorps/buttercoin-master/bin/dev-standalone:6:1, <js>:4:16)
  at Object.<anonymous> (/usr/home/ghostcorps/buttercoin-master/bin/dev-standalone:14:4)
  at Module._compile (module.js:456:26)

npm ERR! buttercoin@0.0.3 start: `bin/dev-standalone`
npm ERR! `sh "-c" "bin/dev-standalone"` failed with 1
npm ERR!
npm ERR! Failed at the buttercoin@0.0.3 start script.
npm ERR! This is most likely a problem with the buttercoin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bin/dev-standalone
npm ERR! You can get their info via:
npm ERR!     npm owner ls buttercoin
npm ERR! There is likely additional logging output above.

npm ERR! System FreeBSD 8.3-RELEASE-p3
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /usr/home/ghostcorps/buttercoin-master
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/home/ghostcorps/buttercoin-master/npm-debug.log
npm ERR! not ok code 0

I am not a programmer but if you are interested in getting it going in FreeBSD I would be glad to help however I can :)

**Comment by enki** [comment]
The code is in flux and changing - it's not related to FreeBSD! Thank you for reporting!

**Comment by ghost2501** [comment]
Ahh k, thanks for the quick reply :)

Have a good day
D

**Comment by PartTimeLegend** [comment]
If you would like to contribute instructions for FreeBSD you are more than welcome.

**Comment by ghost2501** [comment]
Thanks,

There were no actual differences in the process as far as I could tell. The
dependencies are the same also.

This is why I posted, I was wondering if there should be any additional
steps. If I get it working I will post up some instructions.
