### ISSUE TITLE
buttercoin doesn't build on ubuntu

### ISSUE THREAD

**Issue by nranjan** [buttercoin/buttercoin#54]
Hi, I am trying to start a buttecoin instance on an Ubuntu 12.04 LTS system. However I'm getting this error when  I try to do that:

> bignum@0.6.0 install /home/nranjan/buttercoin/node_modules/buttercoin-engine/node_modules/bignum
> node-gyp configure build

sh: 1: node-gyp: not found
npm ERR! error installing bignum@0.6.0
npm ERR! error installing buttercoin-engine@0.0.3

npm ERR! bignum@0.6.0 install: `node-gyp configure build`
npm ERR! `sh "-c" "node-gyp configure build"` failed with 127
npm ERR! 
npm ERR! Failed at the bignum@0.6.0 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.2.0-32-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/nranjan/buttercoin
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message bignum@0.6.0 install: `node-gyp configure build`
npm ERR! message `sh "-c" "node-gyp configure build"` failed with 127
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nranjan/buttercoin/npm-debug.log
npm not ok

**Comment by enki** [comment]
your node version is < 0.10
