### ISSUE TITLE
Error "Not implemented"

### ISSUE THREAD

**Issue by kazi308** [buttercoin/buttercoin#57]
Hi I have installed buttercoin using the github docs on Mac os x, Ubuntu and using the Vagrant vm.

Here is the out put from Mac os x 10.8.4:

sudo npm test

> buttercoin@0.0.3 test /Users/test/project/buttercoin
> sh test.sh

  EWS
    ◦ should listen and be connectable: STARTING
13:06:07.199 - INFO - ProcessingChainEntrance - Starting PCE
13:06:07.205 - INFO - ProcessingChainEntrance - Bumping serial to: 0
13:06:07.207 - INFO - ProcessingChainEntrance - Bumping serial to: 1
13:06:07.208 - INFO - ProcessingChainEntrance - Bumping serial to: 2
13:06:07.208 - INFO - ProcessingChainEntrance - Bumping serial to: 3
13:06:07.208 - INFO - ProcessingChainEntrance - Bumping serial to: 4
13:06:07.208 - INFO - ProcessingChainEntrance - Bumping serial to: 5
13:06:07.209 - INFO - ProcessingChainEntrance - Bumping serial to: 6
13:06:07.209 - INFO - ProcessingChainEntrance - Bumping serial to: 7
13:06:07.209 - INFO - ProcessingChainEntrance - Bumping serial to: 8
13:06:07.210 - INFO - ProcessingChainEntrance - FORWARDING 5
13:06:07.210 - INFO - ProcessingChainEntrance - FORWARDING 10
13:06:07.210 - INFO - ProcessingChainEntrance - FORWARDING 15
13:06:07.210 - INFO - ProcessingChainEntrance - FORWARDING 20
13:06:07.210 - INFO - ProcessingChainEntrance - FORWARDING 25
13:06:07.210 - INFO - ProcessingChainEntrance - FORWARDING 30
13:06:07.211 - INFO - ProcessingChainEntrance - FORWARDING 35
13:06:07.211 - INFO - ProcessingChainEntrance - FORWARDING 40
13:06:07.211 - INFO - ProcessingChainEntrance - FORWARDING 45
13:06:07.212 - INFO - ProcessingChainEntrance - INITIALIZED/REPLAYED LOG
13:06:07.212 - INFO - WebsocketListener - LISTENING
13:06:07.216 - INFO - started
13:06:07.216 - INFO - InitiatorProtocol - STARTING PROTOCOL
13:06:07.217 - INFO - Initiator - Connection #0 - STARTING TO CONNECT: ws://localhost:6150/
13:06:07.229 - INFO - WebsocketListener - Connection #1 - handle_open
13:06:07.230 - INFO - EngineProtocol - STARTING PROTOCOL
13:06:07.233 - INFO - Initiator - Connection #0 - handle_open
13:06:07.234 - INFO - Initiator - Connection #0 - ONCEOPEN
13:06:07.238 - INFO - ProcessingChainEntrance - Bumping serial to: 9
13:06:07.239 - INFO - ProcessingChainEntrance - FORWARDING 50
13:06:07.239 - INFO - EngineProtocol - PCE COMPLETED { operation: 
   { kind: 'ADD_DEPOSIT',
     account: 'peter',
     amount: '5',
     currency: 'BTC',
     opid: '0m81rok19t9fj00z7ahcq1jepznm',
     serial: 9 },
  retval: '50' }
1
13:06:07.242 - INFO - GOT RETVAL { operation: 
   { kind: 'ADD_DEPOSIT',
     account: 'peter',
     amount: '5',
     currency: 'BTC',
     opid: '0m81rok19t9fj00z7ahcq1jepznm',
     serial: 9 },
  retval: '50' }
    ✓ should listen and be connectable 
CLEANING UP
13:06:07.244 - INFO - EngineWebsocketServer - SHUTTING DOWN
13:06:07.244 - INFO - EngineWebsocketServer - LISTENER CLOSED
13:06:07.245 - INFO - WebsocketListener - Connection #1 - CLOSING
13:06:07.245 - INFO - WebsocketListener - Connection #1 - Connection Closed
13:06:07.246 - INFO - EngineProtocol - PROTOCOL CLOSED
13:06:07.246 - INFO - EngineWebsocketServer - ALL CONNS CLOSED
13:06:07.247 - INFO - Initiator - Connection #0 - Connection Closed
13:06:07.248 - INFO - InitiatorProtocol - PROTOCOL CLOSED
13:06:07.248 - WARN - InitiatorProtocol - Connection Lost Not Implemented
13:06:07.248 - INFO - Initiator - Connection #0 - ONCECLOSE
    - should replicate

  1 passing (57 ms)
  1 pending

done

sudo npm start

> buttercoin@0.0.3 start /Users/test/project/buttercoin
> bin/dev-standalone

13:07:48.155 - INFO - ProcessingChainEntrance - Starting PCE
13:07:48.167 - INFO - ProcessingChainEntrance - Bumping serial to: 0
13:07:48.170 - INFO - ProcessingChainEntrance - Bumping serial to: 1
13:07:48.171 - INFO - ProcessingChainEntrance - Bumping serial to: 2
13:07:48.171 - INFO - ProcessingChainEntrance - Bumping serial to: 3
13:07:48.171 - INFO - ProcessingChainEntrance - Bumping serial to: 4
13:07:48.172 - INFO - ProcessingChainEntrance - Bumping serial to: 5
13:07:48.172 - INFO - ProcessingChainEntrance - Bumping serial to: 6
13:07:48.172 - INFO - ProcessingChainEntrance - Bumping serial to: 7
13:07:48.172 - INFO - ProcessingChainEntrance - Bumping serial to: 8
13:07:48.173 - INFO - ProcessingChainEntrance - Bumping serial to: 9
13:07:48.173 - INFO - ProcessingChainEntrance - FORWARDING 5
13:07:48.174 - INFO - ProcessingChainEntrance - FORWARDING 10
13:07:48.174 - INFO - ProcessingChainEntrance - FORWARDING 15
13:07:48.174 - INFO - ProcessingChainEntrance - FORWARDING 20
13:07:48.174 - INFO - ProcessingChainEntrance - FORWARDING 25
13:07:48.174 - INFO - ProcessingChainEntrance - FORWARDING 30
13:07:48.174 - INFO - ProcessingChainEntrance - FORWARDING 35
13:07:48.174 - INFO - ProcessingChainEntrance - FORWARDING 40
13:07:48.175 - INFO - ProcessingChainEntrance - FORWARDING 45
13:07:48.175 - INFO - ProcessingChainEntrance - FORWARDING 50
13:07:48.176 - INFO - ProcessingChainEntrance - INITIALIZED/REPLAYED LOG
13:07:48.177 - INFO - WebsocketListener - LISTENING
13:07:48.180 - INFO - ProcessingChainEntrance - Starting PCE
13:07:48.183 - INFO - ProcessingChainEntrance - PCE LOADING SNAPSHOT
13:07:48.183 - INFO - ProcessingChainEntrance - PCE LOADED SNAPSHOT. EXPECTING SERIAL 8
13:07:48.184 - INFO - ProcessingChainEntrance - INITIALIZED/REPLAYED LOG
13:07:48.184 - INFO - EngineWebsocketSlave - CONNECT UPSTREAM
13:07:48.185 - INFO - SlaveProtocol - STARTING PROTOCOL
13:07:48.186 - INFO - Initiator - Connection #0 - STARTING TO CONNECT: ws://localhost:6150
13:07:48.205 - INFO - WebsocketListener - Connection #1 - handle_open
13:07:48.207 - INFO - EngineProtocol - STARTING PROTOCOL
13:07:48.209 - INFO - Initiator - Connection #0 - handle_open
13:07:48.210 - INFO - EngineWebsocketSlave - CONNECTED
13:07:48.210 - INFO - Initiator - Connection #0 - ONCEOPEN
13:07:48.214 - INFO - EngineProtocol - TAKING PCE SNAPSHOT
13:07:48.215 - INFO - EngineProtocol - SNAPSHOT DONE
1
13:07:48.217 - INFO - SlaveProtocol - SLAVE GOT SNAPSHOT_RESULT
13:07:48.218 - INFO - EngineWebsocketSlave - SLAVE GOT SNAPSHOT
13:07:48.218 - INFO - ProcessingChainEntrance - PCE LOADING SNAPSHOT
13:07:48.218 - INFO - ProcessingChainEntrance - PCE LOADED SNAPSHOT. EXPECTING SERIAL 10
13:07:48.218 - INFO - ProcessingChainEntrance - PCE DUMPING SNAPSHOT
13:07:48.219 - INFO - ProcessingChainEntrance - DONE DUMPING SNAPSHOT
13:07:48.220 - INFO - EngineWebsocketSlave - SLAVE INITIALIZING DOWNSTREAM LISTENER
13:07:48.220 - INFO - WebsocketListener - LISTENING
13:07:48.221 - INFO - EngineWebsocketSlave - QUERY SERVER LISTENING { port: 6151 }
13:07:48.222 - INFO - EngineWebsocketSlave - SLAVE BOOT COMPLETE

The Nodejs version is:
node -v
v0.10.13

from the above output nothing is listening on the port 3000 which I have verifyed using telnet and when I navigate to ports  6151 and 6150 the message  "Not implemented" appears. Am I missing something? Any help is much appreciated.

Please advise.

Thanks for this great project!

**Comment by Nagimesi** [comment]
Hello Kazi308, I encountered the same problem with node v0.10.9 on SuSE 12.1. You made any progress on the issue?

**Comment by kevin-buttercoin** [comment]
Hi Kazi308 and Nagimesi, we are working very hard to complete initial work on this and have it done within the next two weeks.  Thanks for following our project, and once we're done with this push, we will be welcoming community input and taking pull requests again.  We'll also be working on documentation as well.

**Comment by kazi308** [comment]
Hi Kevin-Buttercoin, Thanks for taking the time to respond, I am really looking forward to the results of this project, its great to see that it is actively being worked on. Closing this issue in anticipation for the next release. Cheers.

**Comment by trocker** [comment]
Why was this issue closed? This is a major problem in linux systems... cannot compile the script and is giving the same error as mentioned by @kazi308 . Any workaround for this?

**Comment by suminsudhi** [comment]
still the issue is not resolved it seems  as per above conversation would have solved atleast 4months back
any updates ?
I am get getting issue in arch-linux connecting to port 6151 or 6150 gives not implemented issue
please reopen this one. neither do port 3000 do work as 
any guidance which machine do it works correctly so far tried ubuntu,debian,arch-linux,window7
npm start do work correctly but the port as mentioned do not work.
Please guide how to proceed

**Comment by sunggeorge** [comment]
Same error here on ubuntu 12.04. Is there any update after nearly half a year?
