### ISSUE TITLE
Dead project

### ISSUE THREAD

**Issue by benjiqq** [buttercoin/buttercoin#61]
please fix. thanks.

**Comment by smowden** [comment]
rip

**Comment by kevin-buttercoin** [comment]
We're not dead yet.

http://www.youtube.com/watch?v=grbSQ6O6kbs

(Big announcements coming soon)

**Comment by ing-norante** [comment]
let us know this announcements!

**Comment by bulleric** [comment]
+1

**Comment by benjiqq** [comment]
the architecture wasn't that great anyway. you gotta realize that exchanges are like a monolithic kernel. multikernels don't work for a reason. Some thing applies here. actually the analogy runs pretty deep. the way to do this is to hardcode a kernel in C and then build a webapp around that super efficient core.

**Comment by RevCBH** [comment]
Even the architecture of this project wasn't a parallel approach. The exchange logic itself is entirely monolithic, although I agree the performance is limited drastically by node (at least without a lot of work).

The current architecture is precisely as you suggest (except for the C part, we're using Scala/Java). We have a very efficient trade engine with a API layer for building webapps against. There is an opportunity for parallelization since currency pairs only ever trade against one another, but other than that it's an entirely linear execution engine.

**Comment by PartTimeLegend** [comment]
Some of us have day jobs as well. Until someone offers to pay my salary to do this, I can't be here all the time.

@benjyc You would be surprised what can be done simply and small. Why C? Why not ASM? How about COBOL or Brainfuck? Compilers compile and processors process. If you think you can do better why not fork and submit your improvements?

**Comment by BlueMeanie** [comment]
you guys might be interested in the altchain project: http://altchain.org

**Comment by ghost** [comment]
Also, the following open source Bitcoin Exchange might be interesting to
take a look:

https://bitbucket.org/tmartinx/bitfication

;-)

**Comment by kevin-buttercoin** [comment]
Thanks, guys, we'll check those out.  Hopefully we'll all get to work together on some more stuff.

**Comment by ghost** [comment]
Cool! Nice to know!

I'm the founder of Bitfication.com, I'm running a brazillian Bitcoin
exchange with this code I just posted, hosted on bitbucket. It is a fork of
old BitcoinCentral.net code, powered by Ruby on Rails.

The project needs a lot of code! If you guys have some spare time to work
on it, I can invest some coins!

For example, I would love to integrate Twitter Bootstrap on it, improve
user experience, better procedures for the administrative user but, I'm not
a coder...

Cheers!
Thiago

**Comment by kevin-buttercoin** [comment]
Thiago,
Drop me an email at kevin at buttercoin dot com.  Let's chat some more, I can tell you what we're up to.  Buttercoin is not dead.  Very far from it.  But I'm sure we'll have plenty to talk about and we love keeping strong ties with the bitcoin community, so I'm sure there will be things we can potentially work together on.  I look forward to hearing from you.

Best,
Kevin
