### ISSUE TITLE
buttercoin can't run in ubuntu 13.10 .After npm start ,I cant see "info: Buttercoin front-end server started on http://localhost:3000"

### ISSUE THREAD

**Issue by amo98** [buttercoin/buttercoin#62]
@ubuntu:~/buttercoin$ npm start

> buttercoin@0.0.3 start /home/amo/buttercoin
> bin/dev-standalone

03:10:09.136 - INFO - ProcessingChainEntrance - Starting PCE
03:10:09.164 - INFO - ProcessingChainEntrance - Bumping serial to: 0
03:10:09.181 - INFO - ProcessingChainEntrance - FORWARDING 5
03:10:09.185 - INFO - ProcessingChainEntrance - INITIALIZED/REPLAYED LOG
03:10:09.191 - INFO - WebsocketListener - LISTENING
03:10:09.201 - INFO - ProcessingChainEntrance - Starting PCE
03:10:09.209 - INFO - ProcessingChainEntrance - PCE LOADING SNAPSHOT
03:10:09.210 - INFO - ProcessingChainEntrance - PCE LOADED SNAPSHOT. EXPECTING SERIAL 1
03:10:09.211 - INFO - ProcessingChainEntrance - INITIALIZED/REPLAYED LOG
03:10:09.212 - INFO - EngineWebsocketSlave - CONNECT UPSTREAM
03:10:09.214 - INFO - SlaveProtocol - STARTING PROTOCOL
03:10:09.215 - INFO - Initiator - Connection #0 - STARTING TO CONNECT: ws://localhost:6150
03:10:09.261 - INFO - WebsocketListener - Connection #1 - handle_open
03:10:09.263 - INFO - EngineProtocol - STARTING PROTOCOL
03:10:09.266 - INFO - Initiator - Connection #0 - handle_open
03:10:09.267 - INFO - EngineWebsocketSlave - CONNECTED
03:10:09.268 - INFO - Initiator - Connection #0 - ONCEOPEN
03:10:09.278 - INFO - EngineProtocol - TAKING PCE SNAPSHOT
03:10:09.281 - INFO - EngineProtocol - SNAPSHOT DONE
1
03:10:09.285 - INFO - SlaveProtocol - SLAVE GOT SNAPSHOT_RESULT
03:10:09.286 - INFO - EngineWebsocketSlave - SLAVE GOT SNAPSHOT
03:10:09.286 - INFO - ProcessingChainEntrance - PCE LOADING SNAPSHOT
03:10:09.287 - INFO - ProcessingChainEntrance - PCE LOADED SNAPSHOT. EXPECTING SERIAL 1
03:10:09.287 - INFO - ProcessingChainEntrance - PCE DUMPING SNAPSHOT
03:10:09.300 - INFO - ProcessingChainEntrance - DONE DUMPING SNAPSHOT
03:10:09.301 - INFO - EngineWebsocketSlave - SLAVE INITIALIZING DOWNSTREAM LISTENER
03:10:09.301 - INFO - WebsocketListener - LISTENING
03:10:09.312 - INFO - EngineWebsocketSlave - QUERY SERVER LISTENING { port: 6151 }
03:10:09.321 - INFO - EngineWebsocketSlave - SLAVE BOOT COMPLETE

**Comment by amo98** [comment]
@ubuntu:~/buttercoin$ npm install
npm WARN package.json chained-emitter@0.1.0 No repository field.
npm WARN package.json chained-emitter@0.1.0 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json engine.io-client@0.5.0 No repository field.
npm WARN package.json bytes@0.2.0 No repository field.
npm WARN package.json cookie-signature@1.0.1 No repository field.
npm WARN package.json formidable@1.0.11 No repository field.
npm WARN package.json fresh@0.1.0 No repository field.
npm WARN package.json pause@0.0.1 No repository field.
npm WARN package.json send@0.1.0 No repository field.
npm WARN package.json debug@0.6.0 No repository field.
npm WARN package.json emitter@1.0.0 No repository field.
npm WARN package.json methods@0.0.1 No repository field.
npm WARN package.json range-parser@0.0.4 No repository field.
npm WARN package.json growl@1.7.0 No repository field.
npm WARN package.json weak-map@1.0.0 No repository field.

Maybe because this? Can I fix it?

**Comment by pghalliday** [comment]
the npm warnings are unlikely to be the cause - did you check the node version?

**Comment by amo98** [comment]
0.10.20/17/15/12, the same

**Comment by kevin-buttercoin** [comment]
Thanks for pointing this out, everyone!  Just wanted to remind you that we'll be releasing a scala-based version of this exchange relatively shortly.  We're just finishing up the final details now.  So hold tight, things are just about to get exciting.

**Comment by amo98** [comment]
what nodejs version that the buttercoin can run on ? v0..10.1 is not ok . what is it, pghalliday?

**Comment by kevin-buttercoin** [comment]
I run 0.10.13, and while I haven't built that node proj in awhile, I didn't use to have a problem.  Give that a try.  Otherwise, I would say be patient and wait for Gen 2.  We really are killing ourselves to get that out to everyone. :)

**Comment by amo98** [comment]
I read the source code. It just has 6150 and 6151 of the websocket for engine. There is NO 3000 HTTP SERVER.

**Comment by Nagimesi** [comment]
I think the frontend was placed on a backburner in favor of the bigger picture i.e. the transactional engine.

**Comment by kevin-buttercoin** [comment]
Though any details I provide could be subject to revision, the 20000 ft view of the plan is to open source the exchange (Scala) repository when we get to a v1.0-ish level.  Along with that, we will be releasing an API and encouraging people to build apps on the Buttercoin platform.  Again, I can't provide any more details at this time because we haven't worked out the specifics of exactly how and in what order we'll be releasing things.  Right now, we have a lot of mundane stuff to get through, like security audits, compliance issues, data source integrations, etc.  But the list is rapidly getting shorter.

Generally speaking, though, I wouldn't worry too much about the old node prototype.  The Scala exchange will be what we'll be supporting in the future.

**Comment by gituser** [comment]
i have pretty much the same issue.

just wanted to give it a shot and see how it looks.

any idea how to solve this? using latest master and using nodejs v0.10.25.

```
buttercoin@dev:~/buttercoin$ npm install
npm WARN package.json chained-emitter@0.1.0 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json engine.io-client@0.5.0 No repository field.
npm http GET https://registry.npmjs.org/bignum/0.6.0
npm http GET https://registry.npmjs.org/node-uuid/1.3.3
npm http 200 https://registry.npmjs.org/bignum/0.6.0
npm http GET https://registry.npmjs.org/bignum/-/bignum-0.6.0.tgz
npm http 200 https://registry.npmjs.org/node-uuid/1.3.3
npm http GET https://registry.npmjs.org/node-uuid/-/node-uuid-1.3.3.tgz
npm http 200 https://registry.npmjs.org/node-uuid/-/node-uuid-1.3.3.tgz
npm http 200 https://registry.npmjs.org/bignum/-/bignum-0.6.0.tgz

> bignum@0.6.0 install /home/buttercoin/buttercoin/node_modules/buttercoin-engine/node_modules/bignum
> node-gyp configure build

make: Entering directory `/home/buttercoin/buttercoin/node_modules/buttercoin-engine/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  SOLINK_MODULE(target) Release/obj.target/bignum.node: Finished
  COPY Release/bignum.node
make: Leaving directory `/home/buttercoin/buttercoin/node_modules/buttercoin-engine/node_modules/bignum/build'
buttercoin-engine@0.0.3 node_modules/buttercoin-engine
├── redblack@0.1.3
├── node-uuid@1.3.3
└── bignum@0.6.0
buttercoin@dev:~/buttercoin$ npm test

> buttercoin@0.0.3 test /home/buttercoin/buttercoin
> sh test.sh


/home/buttercoin/buttercoin/test/test_helper.coffee:1
xports, require, module, __filename, __dirname) { global.chai = require 'chai'
                                                                        ^^^^^^
SyntaxError: Unexpected string
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at files (/home/buttercoin/buttercoin/node_modules/mocha/bin/_mocha:271:3)
  at Array.forEach (native)
  at Object.<anonymous> (/home/buttercoin/buttercoin/node_modules/mocha/bin/_mocha:270:10)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```

**Comment by inrazhtet** [comment]
I have the same exact issue as well and can you let us know if this Version 1 is still deployable. Thanks.

npm test

> buttercoin@0.0.3 test /root/buttercoin
> sh test.sh

/root/buttercoin/test/test_helper.coffee:1
xports, require, module, __filename, __dirname) { global.chai = require 'chai'
                                                                        ^^^^^^
SyntaxError: Unexpected string
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at files (/root/buttercoin/node_modules/mocha/bin/_mocha:271:3)
  at Array.forEach (native)
  at Object.<anonymous> (/root/buttercoin/node_modules/mocha/bin/_mocha:270:10)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

**Comment by novoviking** [comment]
same here
