### ISSUE TITLE
Error "Not implemented"  - Issue #57 resubmission

### ISSUE THREAD

**Issue by trocker** [buttercoin/buttercoin#63]
While trying to compile buttercoin in ubuntu : 

> # npm test
> > sh test.sh
>   EWS
>     ◦ should listen and be connectable: STARTING
> 10:01:25.332 - INFO - ProcessingChainEntrance - Starting PCE
> 10:01:25.336 - INFO - ProcessingChainEntrance - INITIALIZED/REPLAYED LOG
> 10:01:25.337 - INFO - WebsocketListener - LISTENING
> 10:01:25.341 - INFO - started
> 10:01:25.342 - INFO - InitiatorProtocol - STARTING PROTOCOL
> 10:01:25.343 - INFO - Initiator - Connection #0 - STARTING TO CONNECT: ws://localhost:6150/
> 10:01:25.358 - INFO - WebsocketListener - Connection #1 - handle_open
> 10:01:25.360 - INFO - EngineProtocol - STARTING PROTOCOL
> 10:01:25.362 - INFO - Initiator - Connection #0 - handle_open
> 10:01:25.363 - INFO - Initiator - Connection #0 - ONCEOPEN
> 10:01:25.367 - INFO - ProcessingChainEntrance - Bumping serial to: 0
> 10:01:25.369 - INFO - ProcessingChainEntrance - FORWARDING 5
> 10:01:25.369 - INFO - EngineProtocol - PCE COMPLETED { operation: 
>    { kind: 'ADD_DEPOSIT',
>      account: 'peter',
>      amount: '5',
>      currency: 'BTC',
>      opid: '1owpobo0kbd1gc0pdi4k61vyh7vw',
>      serial: 0 },
>   retval: '5' }
> 1
> 10:01:25.372 - INFO - GOT RETVAL { operation: 
>    { kind: 'ADD_DEPOSIT',
>      account: 'peter',
>      amount: '5',
>      currency: 'BTC',
>      opid: '1owpobo0kbd1gc0pdi4k61vyh7vw',
>      serial: 0 },
>   retval: '5' }
>     ✓ should listen and be connectable 
> CLEANING UP
> 10:01:25.374 - INFO - EngineWebsocketServer - SHUTTING DOWN
> 10:01:25.375 - INFO - EngineWebsocketServer - LISTENER CLOSED
> 10:01:25.375 - INFO - WebsocketListener - Connection #1 - CLOSING
> 10:01:25.375 - INFO - WebsocketListener - Connection #1 - Connection Closed
> 10:01:25.376 - INFO - EngineProtocol - PROTOCOL CLOSED
> 10:01:25.376 - INFO - EngineWebsocketServer - ALL CONNS CLOSED
> 10:01:25.377 - INFO - Initiator - Connection #0 - Connection Closed
> 10:01:25.377 - INFO - InitiatorProtocol - PROTOCOL CLOSED
> 10:01:25.378 - WARN - InitiatorProtocol - Connection Lost Not Implemented
> 10:01:25.378 - INFO - Initiator - Connection #0 - ONCECLOSE
>     - should replicate
> 1 passing (58ms)
>   1 pending
> done

Note "1 Pending". After this .... npm start doesn't work

> 10:01:41.538 - INFO - ProcessingChainEntrance - Starting PCE
> 10:01:41.549 - INFO - ProcessingChainEntrance - Bumping serial to: 0
> 10:01:41.551 - INFO - ProcessingChainEntrance - FORWARDING 5
> 10:01:41.553 - INFO - ProcessingChainEntrance - INITIALIZED/REPLAYED LOG
> 10:01:41.555 - INFO - WebsocketListener - LISTENING
> 10:01:41.559 - INFO - ProcessingChainEntrance - Starting PCE
> 10:01:41.563 - INFO - ProcessingChainEntrance - INITIALIZED/REPLAYED LOG
> 10:01:41.563 - INFO - EngineWebsocketSlave - CONNECT UPSTREAM
> 10:01:41.565 - INFO - SlaveProtocol - STARTING PROTOCOL
> 10:01:41.567 - INFO - Initiator - Connection #0 - STARTING TO CONNECT: ws://localhost:6150
> 10:01:41.584 - INFO - WebsocketListener - Connection #1 - handle_open
> 10:01:41.584 - INFO - EngineProtocol - STARTING PROTOCOL
> 10:01:41.586 - INFO - Initiator - Connection #0 - handle_open
> 10:01:41.586 - INFO - EngineWebsocketSlave - CONNECTED
> 10:01:41.586 - INFO - Initiator - Connection #0 - ONCEOPEN
> 10:01:41.589 - INFO - EngineProtocol - TAKING PCE SNAPSHOT
> 10:01:41.590 - INFO - EngineProtocol - SNAPSHOT DONE
> 1
> 10:01:41.591 - INFO - SlaveProtocol - SLAVE GOT SNAPSHOT_RESULT
> 10:01:41.591 - INFO - EngineWebsocketSlave - SLAVE GOT SNAPSHOT
> 10:01:41.591 - INFO - ProcessingChainEntrance - PCE LOADING SNAPSHOT
> 10:01:41.592 - INFO - ProcessingChainEntrance - PCE LOADED SNAPSHOT. EXPECTING SERIAL 1
> 10:01:41.592 - INFO - ProcessingChainEntrance - PCE DUMPING SNAPSHOT
> 10:01:41.595 - INFO - ProcessingChainEntrance - DONE DUMPING SNAPSHOT
> 10:01:41.595 - INFO - EngineWebsocketSlave - SLAVE INITIALIZING DOWNSTREAM LISTENER
> 10:01:41.596 - INFO - WebsocketListener - LISTENING
> 10:01:41.597 - INFO - EngineWebsocketSlave - QUERY SERVER LISTENING { port: 6151 }
> 10:01:41.598 - INFO - EngineWebsocketSlave - SLAVE BOOT COMPLETE

After this, nothing happens and the service is not started on any port but 6050 and 6051 are being used. Please help.

**Comment by kevin-buttercoin** [comment]
Hi Trocker,
As I was telling @kazi308 in the other thread, we're building a more robust version of this engine using Scala on the JVM.  We have so much to do that it isn't really worth our time to continue supporting what ended up being a cool, but limited, prototype.  We hope to have this ready before the calendar turns over to 2014, and we will aim to provide devs like you with a lot of really cool tools that advance the bitcoin cause.  If you or anyone else reading this have any questions, feel free to email me at kevin at buttercoin.  Or, you can hit us up on Twitter at @buttercoin, or go on the buttercoin reddit page.

Cheers,
Kevin

**Comment by trocker** [comment]
Cool. I'll hit you up then.
