### ISSUE TITLE
Bithub for Disembursement of Donations

### ISSUE THREAD

**Issue by amingilani** [buttercoin/buttercoin#72]
Seeing how there have been next to no commits to this project for the past year, coupled with the project holding 23.01259287 BTC (~$14,330 atm), and @RevCBH [asking for a disbursement scheme](https://github.com/buttercoin/buttercoin/issues/71#issuecomment-47546014) better than having donators prove ownership of sending addresses, i say use [Bithub](https://github.com/WhisperSystems/BitHub).

Afaik, the project seems dead, but this will allow us to put the donations up the way they were intended.

**Comment by amingilani** [comment]
Also, what is buttercoin.com? Is it associated with this project? How come they're using the branding from this project, and would it not be more beneficial to switch to the AGPL?

**Comment by PartTimeLegend** [comment]
+1

**Comment by amingilani** [comment]
[Infact, much better.](https://tip4commit.com/github/buttercoin/buttercoin)
@RevCBH @PartTimeLegend 

Explanation:
Send a tiny bit of the coins to that address.. each new committer gets 1% of the total pool there. **Don't dump all the coins at once.** _1%_ of _23.01259287 BTC_ would be _0.2301259287 BTC_ (~134.99 USD). That's a lot of reward for updating a broken link, or something.

It just works! :smile:

**Comment by PartTimeLegend** [comment]
My issue with using Tip4Commit is that this is a genuinely dead project.

I therefore list this as either a scam to get donations, or the donations already gained for the development should be split equally between the developers.

I await my recompense at 1AjBcNSvnZsn3ESAH491hUbBrwM4Jmcuy9

**Comment by Marak** [comment]
For the sake of amusement, I will also add my address: 1BFuvcSorMyM6nVFaS4v5YPYBFfGooc8WC

I don't have the IRC logs, but I know for a fact I personally solicited at least one donation from @aantonop for the project. He very politely offered to provide direct compensation to me ( in the form of a pizza ), but I insisted he donate BTC to the Buttercoin project instead. He donated what is now worth close to $1,200.

This whole Buttercoin debacle is really sad to me. A couple of greedy individuals took control of the project by buying the rights from the original creator while pushing out everyone else. There is now no working product and no open-source community support around the project.

See also #71 
https://github.com/buttercoin/buttercoin/issues/71

**Comment by PartTimeLegend** [comment]
I believe that the only way that the funds can be evenly distributed is by number of commits. This should also include pull requests one the original developers were removed from the project.

The funds will just sit in perpetuity unless they are distributed in the ideals of the original project.
The donations were accepts to help fund the developers' time and not for some greedy individual to sit upon.

**Comment by PartTimeLegend** [comment]
To bring this to a wider audience I have cross posted this to [Reddit](http://www.reddit.com/r/Buttercoin/comments/2d9l5q/buttercoin_is_a_scam/)

**Comment by pghalliday** [comment]
I'll throw my bitcoin address out there as well seeing as that's what we're doing

17LtnRG4WxRLYBWzrBoEKP3F7fZx8vcAsK

It's a shame things went this way and it feels a little greedy to be chasing it but I do see the principle of what you're trying to achieve

**Comment by PartTimeLegend** [comment]
Oh and for added proof http://www.buttercoin.net/antonybailey.asc is my public key. A repository I no longer have access to.

I therefore label  you @RevCBH aka Rev. C. Bennett Hoffman a scammer. A Reverend no less, a man of God. Let the almighty judge you on your thieving actions.

**Comment by amingilani** [comment]
And to think that this was such as promising project. I was actually looking forward to this.

I'll just throw my own bitcoin address here, even though I deserve nothing, did no development and wouldn't like any coins from those funds at all. But since everyone's doing it, why the heck not!

1LuGg3ms3dn7bdm5mUk7odtrX3VDoaC6CJ

**On a serious note, though: @RevCBH, you can't just sit on 13k worth of BTC, give excuses, and pretend that nothing is amiss. Do you still even have the coins? I demand proof.**

**Comment by PartTimeLegend** [comment]
Did you know that in Seattle, WA where @RevCBH is from that **theft** exceeding $15,000 is concerned Grand Larceny. IANAL, but if anyone wants to take this case up they are more that welcome to include me in a class action.

**Comment by miohtama** [comment]
I don't want to sound like a dick here - I really want to see the Bitcoins credited to the persons who contributed the project. However, donation, by the definition, is giving away something without expecting anything in the return. I am not sure if donations can be considered reimbursable. 

If the project owner is a scumbag scammer then I am not sure if anything can be done to change the past. Move forward and make sure the person's history is well-known when he/she tries to enter to their next "venture".

**Comment by CedricDahl** [comment]
Hello @amingilani, @PartTimeLegend, nice to meet you both.  I run Buttercoin.com and will do my best to respond to your questions while Bennett is away for personal reasons until Friday August 22.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Let me know if I've missed anything and I'll work to get you answers as soon as possible.</p> <ul><li>@amingilani you recommended a disbursement scheme, thanks for your input here.  I'll make sure that this gets Bennett's attention as soon as he's back.  In the meantime, here are a few points which might be helpful: 1) Bennett has actively reached out to the community asking what they'd like done with the contributed bitcoins http://bit.ly/1syWwEP, 2) Per Bennett's last comment on this thread (http://bit.ly/1ostmFN) "It was my understanding that the donated funds would be used for many things, like maintaining infrastructure, paying for feature or bug bounties, etc. If you can point me to an explicit decision on how to disburse the funds, I will act accordingly. In the meantime, I only feel comfortable returning them to the original donators."                                                                                             </li>                                                                                                                                                                                      <li>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @amingilani, to your second question, What is Buttercoin.com?  We're a bitcoin trading platform (in private beta).  In case you're wondering, we'll be open sourcing the trade execution engine Buttercoin uses.  I'm not technical, so I'll wait for Bennett to return to comment on the specific plan here.                                                                                                                                                                                   </li>                                                                                                                                                                                      <li>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  @PartTimeLegend, thanks for posting this to Reddit, we appreciate the communities perspective on these things.  I can tell by your headline that you're not happy with our communication; that's understandable, we've been so busy trying to get Buttercoin.com out the door that we've done a poor job of communicating what's happening with the development of the Buttercoin open source engine.  The work there is ongoing, Bennett will be able to better comment on it when he gets back August 22.</li>

**Comment by Marak** [comment]
@PartTimeLegend - Did you ever sign a contributor license agreement for your contributions? I know I didn't.

Unless you explicitly gave away the rights to your work, you are well within your rights to sue the Buttercoin organization. The entire project is a derivative of the code written in the first month.

My personal opinion is that Buttercoin is vaporware and will never release a public working version. If a working product is actually released I have no qualms against filing a lawsuit. 

Justice demands retribution.

**Comment by CedricDahl** [comment]
@Marak, I don't think we've met previously, nice to digitally meet you.  As far as I know (Bennett will confirm when he returns August 22) the trade execution engine we're using has been created from scratch in Scala on top of the JVM, none of the externally contributed code has been used.

**Comment by Marak** [comment]
Wow @CedricDahl We've meet and talked in person about the development of the Buttercoin project on multiple occasions.

The fact you are pretending we have not discussed the project in detail reaffirms my suspicion of your dishonesty.

The code I wrote was the foundation for this project. Any further works are derivatives based on my ( and other contributors ) original works. You can argue as much as you want about which technology stack you have switched to, but the fact remains we are the original code contributors to the project.

I suggest you do the right thing and remedy this situation while it's still a small problem.

**Comment by krisives** [comment]
> You can argue as much as you want about which technology stack you have switched to, but the fact remains we are the original code contributors to the project.

That doesn't make their new clean-room implementation a derivative work.

While the GPL would prevent them from making changes to the original source and not releasing them, this project is MIT licensed. Also, even if they were to be GPL licensed if it was version 2 they could still keep the code and not _redistribute_ it since they are a web site rendering pages.

But this is MIT licensed code, so their only requirement is to keep the attribution under "Buttercoin Developers" I believe.

What part of the LICENSE do you think has been violated? I'm speaking from a purely neutral point of view here, simply trying to understand the licensing of this project and how it applies to this debacle.

**Comment by joepie91** [comment]
I have to agree with @krisives here. If the situation is as described, it's absolutely a dick move (and I might consider it a 'scam' from a non-legal perspective), but I don't see a license violation.

**Comment by PartTimeLegend** [comment]
Well is Buttercoin.net and Buttercoin.com  the same project? I think not, you even say different code bases.

The donations for **developers'** time was raised for Buttercoin.net and not Buttercoin.com.

All we want is what is due to us. Failure to make reparations is why I believe you to also be a scam shill.

**Comment by PartTimeLegend** [comment]
Also to @CedricDahl please don't close topics that are in active discussion. This is yet more proof that you want to hide the truth.

If you wish to discuss this in person or with my solicitor, who is UK based please let me know and I will forward physical location details.

I still stand by both @CedricDahl and @RevCBH being scammers.

**Comment by krisives** [comment]
There are two separate issues at play here in my opinion:
- Buttercoin as a group soliciting donations. The question is: was this fraudulent? I don't think so because they have yet to take the money and run. We can argue over how well they are using that money, but it's not yet clear any _fraud_ has been committed.
- Buttercoin as a software was an MIT licensed project. The only agreement most have is the LICENSE file in this repository and the title as a member of "Buttercoin Developers" maintaining the attribution.

This does make it somewhat clear why they are focusing on returning the donations. From the perspective of the donators their problems have not yet been solved. In terms of this being a commissioned product, nothing has been fully made yet.

> The donations for developers' time was raised for Buttercoin.net and not Buttercoin.com.

I don't know the original recipient of the donations (I believe it was the guy that sold this project) but what agreement do you have to get paid by him? This is a commissioned good created voluntarily. The license even explicitly denounces you of any responsibilities or warranty.

My point is that them committing fraud and you getting the donations are somewhat at odds with each other.

**Comment by PartTimeLegend** [comment]
@RevCBH already admitted he had control over the coins. So your argument is moot.

Buttercoin.net is the project the funds were raised for and not Buttercoin.com which has no base on Buttercoin.net. My argument and the argument of others here are that we are not a part of Buttercoin.com, we are not employees of Buttercoin.com, we were freelance developers for Buttercoin.net.

Can anyone with access to the original donation address please sign the following message:

I am a huge scammer and I have stolen all your money. Hahaha I am so 1337.

**Comment by krisives** [comment]
For the donators they would probably want a working high-performance trading platform most. If the new implementation that is open-sourced can deliver on that I don't see why they can't keep the funds they had donated to them.

I don't think donators cared who implemented the system as long as it was implemented.

**Comment by PartTimeLegend** [comment]
The donators donated to buttercoin.NET not buttercoin.COM

Allow me to enlighten you on TLDs as you are obviously unaware:
https://en.wikipedia.org/wiki/Top-level_domain

[Redacted, please don't share personal info, even if it's publicly available]

Notice how they are two different cities and a buttercoin organisation was formed. Are the original developers of buttercoin.net a part of this new organisation? Should I expect my relocation package and work visa to come work in my exciting new office?

The point I am making is that buttercoin.net was a scam to gain venture capital to create vapourware whilst stealing from the bad publicity of MtGox.

I wonder what Techcrunch, WSJ, Bloomberg and BI would have to say about this theft of not only money but of intellectual property.

**Comment by krisives** [comment]
I don't think you're going to get much of a response from anyone with methods like that. It's not in their interest to discuss it with you because obviously you have your mind made up.

I'm interested in what kind of agreements are being violated or the license. If you were to take them to court you would have to say which contract was in question, and more specifically how they failed to comply with it.

The news squawking about it won't change that.

If the new project didn't exist and this project was still in a state of having no changes made to it over the last year, would you still want the donations?

**Comment by CedricDahl** [comment]
All donations have been returned to original senders.
http://www.reddit.com/r/Buttercoin/comments/2dhp16/all_donations_returned_to_original_senders/

**Comment by Marak** [comment]
@PartTimeLegend - If you still wish to develop an open-source crypto-currency exchange I built another project which allows for a universal crypto-currency / crypto-asset hosted wallet.

https://github.com/bigcompany/safewallet

We've got tests passing for the majority of user and wallet logic, multiple cryptos are already supported, and the live demo is already managing ~$50,000 in assets.

Considering safewallet already has user and wallet API for multiple cryptos, adding an exchange API would not be a massive amount of work. There are a lot of open-source matching engines we could incorporate such as https://github.com/objectcomputing/liquibook

**Comment by enki** [comment]
As the original author I want to clarify that I didn't sell the project,
but that I was asked to leave by my cofounders.

We had very different visions, and sadly I lost my opportunity to make good
on what I had every intention to do.

**Comment by Marak** [comment]
Undocumented sale. No taxes paid. All done in Bitcoin.

Great job! Lucky that the IRS can't track the transaction.

**Comment by enki** [comment]
I was a co-founder with a vesting schedule owning less than 30% of the company (not enough to maintain control) and left before the cliff, which means I had no claims. They didn't need to buy anything from me.

Lesson learned maybe is to not share control with co-founders that have joined after a project has started. In any case, control has changed and I wish the new team best of luck. 

Bitcoin still needs a good exchange and I hope they or someone else eventually will deliver.

**Comment by PartTimeLegend** [comment]
@enki we discussed things early on. Do you have the private key to the wallet in question?

**Comment by enki** [comment]
Hey Antony! I remember. Thank you for your help and sorry I didn't manage to deliver.

I do not have the private key. I had to relinquish all control when I was asked to leave the company.

Wish things had gone differently. A year ago, we were about a month away from launching the first fully compliant and licensed US exchange when a founder dispute made that impossible.

**Comment by PartTimeLegend** [comment]
So who has the private key now?

**Comment by PartTimeLegend** [comment]
Also might I just add that if none of this code is being used for buttercoin.com then why is the masthead for the organisation pointing to buttercoin.com?

**Comment by pghalliday** [comment]
Personally, I'm happy that the donations were returned and that no one is sitting on them

**Comment by PartTimeLegend** [comment]
We have a list of the donors along with the amounts they sent. What we cannot establish is who holds the private key for the donation address.

I still believe that the original intention of the donations was to share them among the original developers.

If this project has succeeded when I would expect the donations to be distributed among the developers.

**Comment by amingilani** [comment]
I'm happy too that they're no longer sitting on the coins.

Regardless, @CedricDahl, that was a completely dick move. After speaking so earnestly about the community and how you, as an organization, respect the it so much, you basically just said, "fuck the community, instead of discussing it, let's just send the coins back."

This was a horrible way to end a PR risk, and a completely immature way to handle an issue that was still being discussed. I'm sure a lot of us would like to know who was responsible for this silly decision.

@RevCBH's take on waiting to see people prove ownership of private keys may actually have been better than this, because in a way, he would have then been sure the owners still control over the keys, and the coins weren't being sent to oblivion.

Nonetheless, we can't do anything about this anymore. Sorry, @PartTimeLegend, you deserved compensation.

**Comment by PartTimeLegend** [comment]
As the donations have been returned to the original donors. Which is the best outcome I can see. I see no further point in wasting my time with this issue. As I have been removed from the development team, I have no option to close this this issue. I'm sure one of the scammers can close this down now.
